name: Publish Package to npm
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  update_version:
    name: Update version
    if: contains(github.event.pull_request.labels.*.name, 'release-major') || contains(github.event.pull_request.labels.*.name, 'release-minor') || contains(github.event.pull_request.labels.*.name, 'release-patch')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure git credentials
        run: |
          git config --global user.email "echo@randmar.io"
          git config --global user.name "Echo"
      - name: Check if patch release
        if: contains(github.event.pull_request.labels.*.name, 'release-patch')
        run: npm version patch
      - name: Check if minor release
        if: contains(github.event.pull_request.labels.*.name, 'release-minor')
        run: npm version minor
      - name: Check if major release
        if: contains(github.event.pull_request.labels.*.name, 'release-major')
        run: npm version major

  build_and_release:
    name: Build and Release
    needs: update_version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
