name: Publish Package to npm
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  update_version:
    if: contains(github.event.pull_request.labels.*.name, 'release-major') || contains(github.event.pull_request.labels.*.name, 'release-minor') || contains(github.event.pull_request.labels.*.name, 'release-patch')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          for label in "${{ github.event.pull_request.labels.*.name }}"; do
            if [[ $label == *"release-major"* ]]; then
              npm version major
            elif [[ $label == *"release-minor"* ]]; then
              npm version minor
            elif [[ $label == *"release-patch"* ]]; then
              npm version patch
            fi
          done

  build_and_release:
    name: Build and Release
    needs: update_version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
