name: Publish Package to npm
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  build:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && contains(github.event.pull_request.labels.*.name, 'release-major') || contains(github.event.pull_request.labels.*.name, 'release-minor') || contains(github.event.pull_request.labels.*.name, 'release-patch')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - name: Update npm version
        run: |
          if [[ $(echo ${{ github.event.pull_request.labels.*.name }}) == *"release-major"* ]]; then
            npm version major
          elif [[ $(echo ${{ github.event.pull_request.labels.*.name }}) == *"release-minor"* ]]; then
            npm version minor
          elif [[ $(echo ${{ github.event.pull_request.labels.*.name }}) == *"release-patch"* ]]; then
            npm version patch
          fi
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
