name: Publish Package to npm
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  build:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && contains(github.event.pull_request.labels.*.name, 'release-major') || contains(github.event.pull_request.labels.*.name, 'release-minor') || contains(github.event.pull_request.labels.*.name, 'release-patch')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - name: Determine npm version command
        id: version_command
        run: |
          for label in "${{ github.event.pull_request.labels.*.name }}"; do
            if [[ $label == *"release-major"* ]]; then
              echo "version_type=major" >> $GITHUB_OUTPUT
              exit 0
            elif [[ $label == *"release-minor"* ]]; then
              echo "version_type=minor" >> $GITHUB_OUTPUT
              exit 0
            elif [[ $label == *"release-patch"* ]]; then
              echo "version_type=patch" >> $GITHUB_OUTPUT
              exit 0
            fi
          done
          echo "No release label found"
          exit 1
      - name: Run npm version command
        run: npm version ${{ steps.vars.outputs.version_type }}
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
