name: Publish Package to npm
permissions: write-all
on:
  push:
    branches:
      - main
jobs:
  update_version:
    name: Update version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure git credentials
        run: |
          git config --global user.email "echo@randmar.io"
          git config --global user.name "Echo"
      - name: Check if minor release
        run: |
          npm version minor
          git push

  build_and_release:
    name: Build and Release
    needs: update_version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - run: git pull
      - run: npm ci
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
